//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
<<<<<<< HEAD
//     Runtime Version:4.0.30319.18052
=======
//     Runtime Version:4.0.30319.18033
>>>>>>> c4cbce84670eeaaf9c6068c06cad2e4532343d53
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpontaneousControls.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"C:\\GitHub\\SpontaneousControls\\Dependencies\\waxrec.exe\"")]
        public string WaxRecPath {
            get {
                return ((string)(this["WaxRecPath"]));
            }
            set {
                this["WaxRecPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"C:\\GitHub\\SpontaneousControls\\Dependencies\\findcom.exe\"")]
        public string FindComPath {
            get {
                return ((string)(this["FindComPath"]));
            }
            set {
                this["FindComPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public string HardCodedCOM {
            get {
                return ((string)(this["HardCodedCOM"]));
            }
            set {
                this["HardCodedCOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3333")]
        public string HardCodedUDP {
            get {
                return ((string)(this["HardCodedUDP"]));
            }
            set {
                this["HardCodedUDP"] = value;
            }
        }
    }
}
